# This file is for example purposes only. Replace the placeholders with your actual base64 encoded credentials and save file with correct extention - db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret-example # make this db-secret
type: Opaque
data:
  POSTGRES_USER: <base64 encoded username>
  POSTGRES_PASSWORD: <base64 encoded password>